
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit} from 'next/font/google'
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
// import { Toaster } from "sonner";

const outfit=Outfit({subsets:['latin']})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
        <ToastContainer position="top-right" autoClose={5000} pauseOnHover closeOnClick
theme="dark"/>
      </body>
    </html>
    </ClerkProvider>
  );
}
